name: ezhrm
description: A Product Of 30Days Technologies Pvt Ltd.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.8+58

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  upgrader: ^2.8.2
  toast: ^0.1.5
  flutter_automation: ^1.4.0
  getwidget: ^2.0.4
  rxdart: ^0.25.0
  cached_network_image: ^2.3.2+1
  flutter_bloc:
  shared_preferences:
  flip_card: ^0.6.0
  simple_animations: ^1.1.3
  page_transition: ^2.0.5
  fluttertoast: ^8.0.8
  flutter_circular_chart: ^0.1.0
  percent_indicator: ^4.0.0
  flutter_rounded_date_picker: ^2.0.2
  intl: ">=0.15.0 <1.0.0"
  image_picker: ^0.6.7+22
  image: ^2.1.18
  google_sign_in: ^4.5.1
  firebase_messaging: ^7.0.3
  geolocator: ^6.1.0
  google_maps_flutter: ^1.2.0
  esys_flutter_share:
  flutter_calendar: ^0.0.8
  flutter_calendar_carousel: ^1.5.3
  #flutter_styled_toast: ^1.4.0+1
  clay_containers: ^0.3.2
  platform_device_id: ^0.1.1
  #connectivity:
  geocoder: ^0.2.1
  workmanager: ^0.4.1
  background_location: ^0.1.1
  flutter_local_notifications:
  native_state: ^1.1.1
  flutter_foreground_plugin: ^0.4.0
  get_mac:
  folder_file_saver: ^1.0.0+2
  dio: ^3.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  multi_image_picker:
  flutter_absolute_path:
  flutter_widget_from_html: ^0.5.1+5
  flutter_html: ^1.2.0
  webview_flutter:
  flutter_html_to_pdf: ^0.7.0
  flutter_full_pdf_viewer:
  jitsi_meet: ^2.1.0
  permission_handler: ^4.4.0+hotfix.2
  package_info:
  #android_intent: ^0.3.6+12
  otp_text_field: ^1.0.1
  #bitmap: ^0.0.6
  camera: ^0.5.7+2
  provider: ^4.3.3
  highlighter_coachmark: ^0.0.3
  flutter_native_image: ^0.0.5
  adv_fab: ^1.0.5
  device_info:
  data_connection_checker:
  overlay_screen:
  top_snackbar_flutter:
  flutter_animated_dialog:
  path_provider:
  open_file: ^3.0.1
  syncfusion_flutter_pdf: ^19.1.69-beta
  downloads_path_provider_28: ^0.1.0
  pdf_text:
  ext_storage:
  path: ^1.6.4
  path_provider_ex: ^1.0.1
  flutter_file_manager: ^0.2.0
  change_app_package_name: ^1.0.0
  flushbar:
  flutter_exif_rotation: ^0.5.0
  native_device_orientation: ^1.0.0
  flutter_math: ^0.2.1
  screenshot: ^1.2.3
  flutter_lints: ^1.0.4
  flutter_signin_button: ^2.0.0
  social_login_buttons: ^1.0.6+2
  loading_animation_widget: ^1.1.0+5
  font_awesome_flutter: ^9.2.0
  qr_flutter: ^4.0.0
  table_calendar: ^2.3.3
  flutter_snake_navigationbar: ^0.6.1
  flutter_spinkit: ^5.1.0
  file_picker: ^2.1.7
  new_version: ^0.0.1
  app_settings: ^4.1.6
  flutter_background: ^1.1.0
  connectivity_plus: ^0.8.1
  http: ^0.12.2
  # in_app_update: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.8.1"

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/ezlogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/Myriad/Myriad-Pro-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
